name: Image
on:
 push:
    branches: [ main ]

 pull_request:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1 
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Set version number
        run: |
          $version = "3.2."+(4000+$(${{ github.run_number }}))+".0"
          echo $version
          echo "VERSION_NUMBER=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append


