name: CI

on: workflow_dispatch

jobs:
  build_and_push:

    runs-on: docker

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build project with Maven
      run: mvn -B package --file pom.xml
      
    - run: mkdir staging && cp target/*.jar staging  
    - uses: actions/upload-artifact@v1
      with:
        name: Package
        path: staging   
  
    
    - name: Login to DockerHub
      #if: github.event_name != 'pull_request'
      uses: docker/login-action@v1 
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
          
    - name: Build and push 
      uses: docker/build-push-action@v2
      with:
        context: .
        #push: ${{ github.event_name != 'pull_request' }}
        push: true
        tags: |
          ${{ secrets.DOCKER_REPO }}:latest
          ${{ secrets.DOCKER_REPO }}:v${{ github.run_number }}
          
#    - name: Upload image
#      uses: ishworkh/docker-image-artifact-upload@v1
#      with:
#        image: "${{ secrets.DOCKER_REPO }}:v${{ github.run_number }}"

