name: Docker-Master

on: workflow_dispatch

jobs:
  build_and_push:

    #runs-on: ubuntu-latest
    runs-on: [metagen, bhargesh]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build project with Maven
      run: mvn -B package --file pom.xml
      
    - name: zip artifacts
      run: |
        mkdir staging && cp target/*.jar staging  
        ls -lrt staging
        zip -r maven.zip  staging/
        
    - uses: actions/upload-artifact@v1
      with:
        name: Package
        path: staging   
  
    - name: Create GitHub release
      id: create-new-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: r-${{ github.ref_name }}-${{ github.run_number }}
        release_name: Release-${{ github.ref_name }}-${{ github.run_number }}
    
    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-new-release.outputs.upload_url }}
        asset_path: staging/github-action-maven-tutorial-1.0-SNAPSHOT.jar
        asset_name: site-v${{ github.run_number }}.jar
        asset_content_type: application/java-archive
        #asset_path: ./maven.zip
        #asset_name: site-v${{ github.run_number }}.zip
        #asset_content_type: application/zip
    
    - name: Login to DockerHub
      #if: github.event_name != 'pull_request'
      uses: docker/login-action@v1 
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
          
    - name: Build and push 
      uses: docker/build-push-action@v2
      with:
        context: .
        push: ${{ github.ref_name == 'master' }}
        #push: true
        tags: |
          bhargesh/runner:latest
          bhargesh/runner:v${{ github.ref_name }}-${{ github.run_number }}

    - name: Build and push 
      uses: docker/build-push-action@v2
      with:
        context: .
        push: ${{ github.ref_name == 'main' }}
        #push: true
        tags: |
          ${{ secrets.DOCKER_REPO }}:latest
          ${{ secrets.DOCKER_REPO }}:v${{ github.ref_name }}-${{ github.run_number }}
